version: "3"

services:
  db:
    image: postgres:14
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=plannerpassword
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=postgres
    volumes:
      - database-data:/var/lib/postgresql/data/

  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    restart: always

  app:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - SECRET=BvVPucWzVVTVq5eWtviYh3PMzRcGtkfb
      - POSTGRES_URL=postgresql://postgres:plannerpassword@db:5432/postgres
      - REDIRECT_URL=https://developers.google.com/oauthplayground
      - GOOGLE_APPLICATION_CREDENTIALS=secrets/service_account_key.json
    volumes:
      - ./secrets:/app/secrets
      - ./files:/app/files
    depends_on:
      - db
      - redis

volumes:
  database-data:
  redis-data:
